### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by frakman1** [shadyabhi/IMDb-Ratings-Viewer#3]
Google Chrome version: 77.0.3865.90 (Official Build) (64-bit)
MacBookPro: 

![image](https://user-images.githubusercontent.com/5826484/73417368-d82d1a80-42e5-11ea-96c3-950b4a459238.png)

I just installed it on my Mac. Went to imdb (even tried on a new browser window) and there is no change. Note the extension is shown on the toolbar:

![image](https://user-images.githubusercontent.com/5826484/73417420-feeb5100-42e5-11ea-97f6-72ea45af6903.png)

See screenshot below:

![image](https://user-images.githubusercontent.com/5826484/73417336-bd5aa600-42e5-11ea-9f5e-82e8c23fe543.png)

**Comment by shadyabhi** [comment]
Thanks @frakman1  for reporting this. This stopped working because of Chrome's API changes. I'll take a look at this over the weekend.

**Comment by frakman1** [comment]
Thank you for still working on this. I thought this project was abandoned since it's over 4 years old.

**Comment by frakman1** [comment]
Any luck?

**Comment by shadyabhi** [comment]
@frakman1  I briefly looked at it and the extension is broken because of change in Chrome's API. I used kango framework to create the extension for various browsers but it looks like that toolkit is now dead. 
https://github.com/KangoExtensions/kango

I tried to look for alternatives to this extension but couldn't find a clear winner. Is there one? If there isn't, I'll work on making it work again.

**Comment by nascentt** [comment]
Hi, I just found your github. Just wanted to let you know in case you didn't know.  The extension's been removed from google webstore, I get 404 when I go to the webstore page (although it's still installed on my chrome despite not functioning).

That being said.  I've been using https://chrome.google.com/webstore/detail/my-imdb/ngicopfkgbodejbbfalbmobdpjebhhmb which works in the same way and works quite well.
However, it doesn't have the first decimal place like you had, so depending on whether you miss the decimal or not it might not be an adequate replacement.

**Comment by frakman1** [comment]
That didn't work for me either. Nothign shows up when I go to imdb. I even enabled it in Incognito and tried it there. No luck.

**Comment by shadyabhi** [comment]
Sorry, everyone to hold you guys for too long. This code was written 6 years ago and then I didn't get a chance to maintain it. 

Having said that, since we got some recent activity on this issue, **I am taking a look at it right now** since that seems like a good thing to do on a Friday evening during the lockdown 😂

**Comment by shadyabhi** [comment]
Hey everyone, I've uploaded the latest code that works. I also submitted for publishing in Chrome Web Store, it's currently under review since it got deactivated due to manifest version issue. I'm unsure how long a fresh review takes, until then, you can simply load the extension from "src" folder in the Git repo.

**Comment by nascentt** [comment]
You  absolute legend. It works! (I'm using the unpacked extension src folder). Let us know when it's in chrome store and I'll switch over to that.

Also, I should note I made a mistake above, the other extension I linked to shows "your ratings" on movies, not the average ratings.  My bad, nicely both extensions work together so I'm using both now.

**Comment by frakman1** [comment]
@shadyabhi I can confirm that this works now. I used the Settings->Extensions->Load Unpacked option to install it and can now see the ratings badges next to all movies. Well done!

![image](https://user-images.githubusercontent.com/5826484/88459549-43eedb00-ce64-11ea-8d0e-6fe8ad1d428b.png)


![image](https://user-images.githubusercontent.com/5826484/88459593-93cda200-ce64-11ea-898e-fb0d23ca4d21.png)

**Comment by shadyabhi** [comment]
Thanks @nascentt and @frakman1 . I'm happy to be of help :)

**Comment by shadyabhi** [comment]
@nascentt @frakman1 Extension is now on play store again! 

https://chrome.google.com/webstore/detail/imdb-ratings-viewer/daaoegihbflfijkdhalidlmochdbobgb

**Comment by nascentt** [comment]
Thanks @shadyabhi !
